apiVersion: v1
kind: Namespace
metadata:
  name: debug
  labels:
    project: roboshop
    environment: dev
    purpose: poc
---



apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: debug
  labels:
    app: debug
    project: roboshop
    environment: dev
    purpose: poc

spec:
  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
    