apiVersion: v1
kind: Namespace
metadata:
  name: redisdb
  labels:
    project: roboshop
    environment: dev
    purpose: poc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    environment: dev
    purpose: poc

  annotations:
    kubernetes.io/change-cause: "v1 redis deployment"

    # the namespace in which the deployment will be created 
spec:
  replicas: 1
  selector:
    matchLabels:
      
      app: redis
      project: roboshop
      environment: dev
      purpose: poc

# the pod template

  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        environment: dev
        purpose: poc
    spec:
      containers:
      - name: redisdb
        image: redis:latest
        ports:
        - containerPort: 5679

---

#nodeport service


apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    purpose: poc

spec:
  type: ClusterIP
  selector:
    app: redis
    project: roboshop
    environment: dev
    purpose: poc 
  ports:
  - protocol: TCP
    port: 5679  #service port
    targetPort: 5679 #container port